### ISSUE TITLE
Username / password for pre-built images?

### ISSUE THREAD

**Issue by jwillikers** [bengtfredh/pinebook-pro-fedora-installer#25]
What is the username  and password for the pre-built images? The graphical display doesn't appear for logging in, but I have console access. I just need the credentials to log in. Thanks!

**Comment by bengtfredh** [comment]
What image are you using? There is no user/password configured. root have a password set from a generated string during create. No one have that password. In my testing I have got a run first dialogue to create user and set password. I need to test again to verify.
There is no good way to reset password unless you can mount the boot partition on another computer and change the boot command line. You can probably add rd.break, remount / with rw. 
I will recommend to use the script anyway, if that can work for you.

**Comment by jwillikers** [comment]
I was using the `Fedora-Workstation-34-1.2-btrfs-kernel-pbp.img` image. I am using the script to generate my own image at the moment and will see if that works.

**Comment by jwillikers** [comment]
Building from the script worked great! It looks beautiful and runs way better than I'd expect off the SD card. I'll be flashing this to the eMMC next. Thanks!!!

**Comment by bengtfredh** [comment]
That is great. I agree, Fedora runs very nice on the Pinebook Pro. I am glad it worked out good for you.
