### ISSUE TITLE
BUG: Overlay permissions

### ISSUE THREAD

**Issue by westurner** [bengtfredh/pinebook-pro-fedora-installer#4]
I had to do this to get the system to boot (and to e.g. get audio to work) due to permission errors in `less -R /var/log/boot.log` and `journalctl --file=/var/log/journal/system.journal` : 

```bash
for f in $(find ./overlays | sed 's,./overlays,,g'); do sudo chmod -v o+rx $f; done

# this would work, too:
sudo chmod -v o+rx $(find ./overlays | sed 's,./overlays,,g')
```

Possible solutions that could eliminate the need for the permissions fix:
- set umask (`help umask` / `info umask`) before `cp`-ing in the overlays
- `install` (`man install`) is one alternative way to cp files into place and set permissions (the default `--mode` is `rwxr-xr-x`)

**Comment by westurner** [comment]
... the file perms don't need to be executable, so a more complex find command or multiple find commands are necessary

**Comment by bengtfredh** [comment]
Do you run script with sudo or as root? I have always run as root so experience can be different.

git clone will pull down right file mode. So probably good idea to make sure files has right mode before commit, and change cp to cp -af to preserve file mode.

**Comment by westurner** [comment]
I'll try to remember to boot the latest manjaro from the sd card that I installed to eMMC from and check what the default permissions of the git cloned files were before the cp.

I don't think I could've successfully run the script without sudo.

Git respects umask when cloning: 
https://stackoverflow.com/questions/10637416/git-clone-respects-umask-except-for-top-level-project-directory
