### ISSUE TITLE
pacman: segmentation fault

### ISSUE THREAD

**Issue by ovv** [bengtfredh/pinebook-pro-fedora-installer#6]
I'm testing this script from a fedora 32 laptop and pacman in the manjaro systemd container fails with a segmentation fault.

```
:: Synchronizing package databases...
debug: url: https://manjaro.moson.org/arm-stable/core/aarch64/core.db
debug: maxsize: 134217728
debug: opened tempfile for download: /var/lib/pacman/sync/core.db.part (wb)

error: segmentation fault
Please submit a full bug report with --debug if appropriate.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
```

Anyone else get this ?

**Comment by bengtfredh** [comment]
I can confirm - same error. There is an issue with pacman-key.

**Comment by bengtfredh** [comment]
Script is using Manjaro-ARM-aarch64-latest.tar.gz as base for installing kernel and this image have issues with pacman. I have reported it as en issue with Manjaro team.

https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-installer/-/issues/28

**Comment by bengtfredh** [comment]
Manjaro team created a new Manjaro-ARM-aarch64-latest.tar.gz to fix missing dependencies for pacman-key. pacman-mirrors still fails. Scipt can run without pacman-mirrors update mirrors, so that can be commented out.
